#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LocationRewards.Resource", IsApplication=true)]

namespace LocationRewards
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int blueclick = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int disabledText = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int greenhighlighttext = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int greyheadertext = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accept = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_rating_star_off_normal_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_rating_star_on_normal_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_star_off_normal_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_star_off_normal_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_star_on_normal_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Buy = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int drawer_shadow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int EatingOut = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int EatingOutSmall = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Fun = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int FunSmall = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int HomeAndEssentials = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int HomeAndEssentialsSmall = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_attach = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_call = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_copy = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_cut = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_delete = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_done = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_edit = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_locate = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_action_mail = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_action_mail_add = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_action_map = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_action_microphone = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_overflow = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_action_paste = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_action_photo = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_action_refresh = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_action_search = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_action_select_all = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_action_send = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_action_sessions = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_action_share = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_action_speakers = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_action_star = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_action_user = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_action_user_add = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_action_video = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_action_whats_on = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_btn_search = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_drawer = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_launcher = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_menu_search = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_menu_search_holo_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_menu_search_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_menu_star = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_search = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_search_api_holo_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_tab_my_schedule = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_tab_sessions = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_tab_speakers = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_tab_whats_on = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Icon = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Lifestyle = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int LifestyleSmall = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int loginbox = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int monoandroidsplash = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int MSNPeople = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int Placeholder = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int questionmark = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Redeem = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int Travel = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int TravelSmall = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int twitter = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int XamarinTitle = 2130837571;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001d
			public const int DetailsTextView = 2131296285;
			
			// aapt resource value: 0x7f09001f
			public const int Divider = 2131296287;
			
			// aapt resource value: 0x7f090004
			public const int EmailButton = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int HeaderTextView = 2131296261;
			
			// aapt resource value: 0x7f09001e
			public const int ImageButton = 2131296286;
			
			// aapt resource value: 0x7f090027
			public const int MenuFavorite = 2131296295;
			
			// aapt resource value: 0x7f090026
			public const int MenuSearch = 2131296294;
			
			// aapt resource value: 0x7f090003
			public const int NameTextView = 2131296259;
			
			// aapt resource value: 0x7f090020
			public const int PhoneButton = 2131296288;
			
			// aapt resource value: 0x7f090002
			public const int ValueTextView = 2131296258;
			
			// aapt resource value: 0x7f090009
			public const int cat_imageView1 = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int cat_imageView2 = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int cat_imageView3 = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int cat_imageView4 = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int cat_imageView5 = 2131296273;
			
			// aapt resource value: 0x7f090013
			public const int datePicker1 = 2131296275;
			
			// aapt resource value: 0x7f090025
			public const int emptyTextView = 2131296293;
			
			// aapt resource value: 0x7f090023
			public const int fragmentContainer = 2131296291;
			
			// aapt resource value: 0x7f090000
			public const int linearLayout1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int linearLayout2 = 2131296257;
			
			// aapt resource value: 0x7f09001b
			public const int payButton = 2131296283;
			
			// aapt resource value: 0x7f090007
			public const int productImageView = 2131296263;
			
			// aapt resource value: 0x7f090024
			public const int progressBar1 = 2131296292;
			
			// aapt resource value: 0x7f09001a
			public const int radioButton1 = 2131296282;
			
			// aapt resource value: 0x7f090016
			public const int radioButton6 = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int radioButton7 = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int radioButton8 = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int radioButton9 = 2131296281;
			
			// aapt resource value: 0x7f090015
			public const int radioGroup1 = 2131296277;
			
			// aapt resource value: 0x7f090022
			public const int rewardsImageView = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int rewardsTextView = 2131296289;
			
			// aapt resource value: 0x7f090008
			public const int textView1 = 2131296264;
			
			// aapt resource value: 0x7f09000a
			public const int textView2 = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int textView3 = 2131296268;
			
			// aapt resource value: 0x7f09000e
			public const int textView4 = 2131296270;
			
			// aapt resource value: 0x7f090010
			public const int textView5 = 2131296272;
			
			// aapt resource value: 0x7f090014
			public const int textViewChoosePayment = 2131296276;
			
			// aapt resource value: 0x7f090012
			public const int textViewDelSlot = 2131296274;
			
			// aapt resource value: 0x7f09001c
			public const int textViewOrderStatus = 2131296284;
			
			// aapt resource value: 0x7f090006
			public const int view1 = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EmailPropertyListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GroupHeaderListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ImagePropertyListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PartnerProducts = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PartnerProductsList = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PaymentOptions = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PersonListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PhonePropertyListItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PropertyListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int RewardsFragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RewardsFrame = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SearchActivity = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SectionHeader = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int TraderPartnerLocationsList = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int TwitterPropertyListItem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int UrlPropertyListItem = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int AppActivityOptionsMenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int TradingPartnerActivityOptionsMenu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060006
			public const int FavoritesTabTitle = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int MenuFavorite = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int MenuSearch = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int NoFavoritesText = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int NoSearchResultsText = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int SearchHint = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int SearchTabTitle = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int SearchingText = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int hello = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int sessions_tab_label = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int speakers_tab_label = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int whatson_tab_label = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int CustomHoloTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Mono_Android_Theme_Splash = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int searchable = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
